import { Grievance } from "./types";

export const locations = [
  "Mumbai Central",
  "Delhi NCR",
  "Bangalore South",
  "Chennai West",
  "Kolkata North",
  "Hyderabad East",
  "Pune Central",
  "Ahmedabad",
  "Jaipur",
  "Lucknow"
];

export const sampleGrievances: Grievance[] = [
  {
    id: "GRV-001",
    originalText: "There is a massive pothole near the school entrance on MG Road causing accidents daily.",
    translatedText: "There is a massive pothole near the school entrance on MG Road causing accidents daily.",
    detectedLanguage: "English",
    location: "Mumbai Central",
    category: "roads",
    categoryReasoning: "Identified as 'roads' based on keywords: 'pothole, road'.",
    priority: "Critical",
    priorityReasoning: "Emergency situation detected: 'accident'. Immediate action required.",
    department: "Public Works",
    routingReasoning: "Routed to Public Works as the primary authority for roads-related issues in Mumbai Central.",
    associatedSchemes: ["Pradhan Mantri Gram Sadak Yojana", "Smart Cities Mission"],
    status: "In Progress",
    submittedAt: new Date("2025-12-28T10:30:00"),
    submittedBy: "Citizen-4521"
  },
  {
    id: "GRV-002",
    originalText: "No water supply for the past 3 days in our area. Children are falling sick.",
    translatedText: "No water supply for the past 3 days in our area. Children are falling sick.",
    detectedLanguage: "English",
    location: "Delhi NCR",
    category: "water",
    categoryReasoning: "Identified as 'water' based on keywords: 'water, supply'.",
    priority: "High",
    priorityReasoning: "Urgent issue identified: 'no water'. Requires prompt attention.",
    department: "Water Resources",
    routingReasoning: "Routed to Water Resources as the primary authority for water-related issues in Delhi NCR.",
    associatedSchemes: ["Jal Jeevan Mission", "Atal Mission for Rejuvenation"],
    status: "Pending",
    submittedAt: new Date("2025-12-29T14:20:00"),
    submittedBy: "Citizen-7823"
  },
  {
    id: "GRV-003",
    originalText: "सड़क में बड़ा गड्ढा है जिसमें कल एक बाइक वाला गिर गया",
    translatedText: "There is a big pothole in the road where a bike rider fell yesterday",
    detectedLanguage: "Hindi",
    location: "Jaipur",
    category: "roads",
    categoryReasoning: "Identified as 'roads' based on keywords: 'pothole, road'.",
    priority: "High",
    priorityReasoning: "Urgent issue identified: 'danger'. Requires prompt attention.",
    department: "Public Works",
    routingReasoning: "Routed to Public Works as the primary authority for roads-related issues in Jaipur.",
    associatedSchemes: ["Pradhan Mantri Gram Sadak Yojana", "Smart Cities Mission"],
    status: "Pending",
    submittedAt: new Date("2025-12-30T09:15:00"),
    submittedBy: "Citizen-3421"
  },
  {
    id: "GRV-004",
    originalText: "Garbage has been piling up for a week. Terrible smell and health hazard.",
    translatedText: "Garbage has been piling up for a week. Terrible smell and health hazard.",
    detectedLanguage: "English",
    location: "Bangalore South",
    photoUrl: "https://images.unsplash.com/photo-1605600659908-0ef719419d41?w=400",
    category: "sanitation",
    categoryReasoning: "Identified as 'sanitation' based on keywords: 'garbage, smell'.",
    priority: "High",
    priorityReasoning: "Urgent issue identified: 'danger'. Requires prompt attention.",
    department: "Sanitation & Waste",
    routingReasoning: "Routed to Sanitation & Waste as the primary authority for sanitation-related issues in Bangalore South.",
    associatedSchemes: ["Swachh Bharat Mission", "Clean India Campaign"],
    status: "In Progress",
    submittedAt: new Date("2025-12-30T11:45:00"),
    submittedBy: "Citizen-9012"
  },
  {
    id: "GRV-005",
    originalText: "Fire broke out in the market area. Need immediate help!",
    translatedText: "Fire broke out in the market area. Need immediate help!",
    detectedLanguage: "English",
    location: "Chennai West",
    category: "safety",
    categoryReasoning: "Identified as 'safety' based on keywords: 'fire, emergency'.",
    priority: "Critical",
    priorityReasoning: "Emergency situation detected: 'fire, emergency'. Immediate action required.",
    department: "Police",
    routingReasoning: "Routed to Police as the primary authority for safety-related issues in Chennai West.",
    associatedSchemes: ["Safe City Project", "Emergency Response Support System"],
    status: "Escalated",
    submittedAt: new Date("2025-12-31T16:30:00"),
    submittedBy: "Citizen-5678"
  },
  {
    id: "GRV-006",
    originalText: "The government hospital has no medicines. Patients are suffering.",
    translatedText: "The government hospital has no medicines. Patients are suffering.",
    detectedLanguage: "English",
    location: "Kolkata North",
    category: "healthcare",
    categoryReasoning: "Identified as 'healthcare' based on keywords: 'hospital, medicine'.",
    priority: "High",
    priorityReasoning: "Urgent issue identified: 'immediate'. Requires prompt attention.",
    department: "Health Department",
    routingReasoning: "Routed to Health Department as the primary authority for healthcare-related issues in Kolkata North.",
    associatedSchemes: ["Ayushman Bharat", "National Health Mission"],
    status: "Pending",
    submittedAt: new Date("2025-12-31T08:00:00"),
    submittedBy: "Citizen-2345"
  },
  {
    id: "GRV-007",
    originalText: "Street lights not working for 2 months. Area is very dark and unsafe at night.",
    translatedText: "Street lights not working for 2 months. Area is very dark and unsafe at night.",
    detectedLanguage: "English",
    location: "Hyderabad East",
    category: "roads",
    categoryReasoning: "Identified as 'roads' based on keywords: 'street, light'.",
    priority: "Medium",
    priorityReasoning: "Moderate concern detected: 'not working'. Should be addressed soon.",
    department: "Public Works",
    routingReasoning: "Routed to Public Works as the primary authority for roads-related issues in Hyderabad East.",
    associatedSchemes: ["Pradhan Mantri Gram Sadak Yojana", "Smart Cities Mission"],
    status: "Pending",
    submittedAt: new Date("2026-01-01T10:00:00"),
    submittedBy: "Citizen-6789"
  },
  {
    id: "GRV-008",
    originalText: "தண்ணீர் குழாய் உடைந்து தண்ணீர் வீணாகிறது",
    translatedText: "Water pipe is broken and water is getting wasted",
    detectedLanguage: "Tamil",
    location: "Chennai West",
    category: "water",
    categoryReasoning: "Identified as 'water' based on keywords: 'water, pipe'.",
    priority: "High",
    priorityReasoning: "Urgent issue identified: 'broken'. Requires prompt attention.",
    department: "Water Resources",
    routingReasoning: "Routed to Water Resources as the primary authority for water-related issues in Chennai West.",
    associatedSchemes: ["Jal Jeevan Mission", "Atal Mission for Rejuvenation"],
    status: "In Progress",
    submittedAt: new Date("2026-01-01T12:30:00"),
    submittedBy: "Citizen-1234"
  },
  {
    id: "GRV-009",
    originalText: "School building is in dangerous condition. Walls are cracking.",
    translatedText: "School building is in dangerous condition. Walls are cracking.",
    detectedLanguage: "English",
    location: "Pune Central",
    photoUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400",
    category: "education",
    categoryReasoning: "Identified as 'education' based on keywords: 'school, building'.",
    priority: "Critical",
    priorityReasoning: "Emergency situation detected: 'collapse, danger'. Immediate action required.",
    department: "Education Board",
    routingReasoning: "Routed to Education Board as the primary authority for education-related issues in Pune Central.",
    associatedSchemes: ["Sarva Shiksha Abhiyan", "Mid Day Meal Scheme", "Digital India"],
    status: "Escalated",
    submittedAt: new Date("2026-01-01T14:00:00"),
    submittedBy: "Citizen-8901"
  },
  {
    id: "GRV-010",
    originalText: "Theft cases increasing in our locality. No police patrolling.",
    translatedText: "Theft cases increasing in our locality. No police patrolling.",
    detectedLanguage: "English",
    location: "Ahmedabad",
    category: "safety",
    categoryReasoning: "Identified as 'safety' based on keywords: 'theft, crime, police'.",
    priority: "High",
    priorityReasoning: "Urgent issue identified: 'crime, theft'. Requires prompt attention.",
    department: "Police",
    routingReasoning: "Routed to Police as the primary authority for safety-related issues in Ahmedabad.",
    associatedSchemes: ["Safe City Project", "Emergency Response Support System"],
    status: "In Progress",
    submittedAt: new Date("2026-01-02T09:00:00"),
    submittedBy: "Citizen-3456"
  },
  {
    id: "GRV-011",
    originalText: "रस्ता खराब आहे आणि पाऊस पडला की पाणी साचते",
    translatedText: "The road is bad and water accumulates when it rains",
    detectedLanguage: "Marathi",
    location: "Pune Central",
    category: "roads",
    categoryReasoning: "Identified as 'roads' based on keywords: 'road'.",
    priority: "Medium",
    priorityReasoning: "Moderate concern detected: 'damaged'. Should be addressed soon.",
    department: "Public Works",
    routingReasoning: "Routed to Public Works as the primary authority for roads-related issues in Pune Central.",
    associatedSchemes: ["Pradhan Mantri Gram Sadak Yojana", "Smart Cities Mission"],
    status: "Pending",
    submittedAt: new Date("2026-01-02T11:30:00"),
    submittedBy: "Citizen-7890"
  },
  {
    id: "GRV-012",
    originalText: "Need ration card renewal. Office staff asking for bribe.",
    translatedText: "Need ration card renewal. Office staff asking for bribe.",
    detectedLanguage: "English",
    location: "Lucknow",
    category: "administrative",
    categoryReasoning: "Identified as 'administrative' based on keywords: 'ration, card, bribe, corruption'.",
    priority: "High",
    priorityReasoning: "Corruption complaint requires immediate investigation.",
    department: "Municipal Office",
    routingReasoning: "Routed to Municipal Office as the primary authority for administrative-related issues in Lucknow.",
    associatedSchemes: ["e-Governance Initiative", "Digital Locker"],
    status: "Pending",
    submittedAt: new Date("2026-01-02T14:00:00"),
    submittedBy: "Citizen-2345"
  },
  {
    id: "GRV-013",
    originalText: "Public toilet near bus stand is extremely dirty. No cleaning for months.",
    translatedText: "Public toilet near bus stand is extremely dirty. No cleaning for months.",
    detectedLanguage: "English",
    location: "Mumbai Central",
    category: "sanitation",
    categoryReasoning: "Identified as 'sanitation' based on keywords: 'toilet, cleaning, dirty'.",
    priority: "Medium",
    priorityReasoning: "Moderate concern detected: 'problem'. Should be addressed soon.",
    department: "Sanitation & Waste",
    routingReasoning: "Routed to Sanitation & Waste as the primary authority for sanitation-related issues in Mumbai Central.",
    associatedSchemes: ["Swachh Bharat Mission", "Clean India Campaign"],
    status: "Pending",
    submittedAt: new Date("2026-01-02T16:00:00"),
    submittedBy: "Citizen-5678"
  },
  {
    id: "GRV-014",
    originalText: "రక్తస్రావం అవుతోంది, అత్యవసర సహాయం కావాలి",
    translatedText: "Bleeding occurring, need emergency help",
    detectedLanguage: "Telugu",
    location: "Hyderabad East",
    category: "healthcare",
    categoryReasoning: "Identified as 'healthcare' based on keywords: 'bleeding, emergency'.",
    priority: "Critical",
    priorityReasoning: "Emergency situation detected: 'bleeding, emergency'. Immediate action required.",
    department: "Health Department",
    routingReasoning: "Routed to Health Department as the primary authority for healthcare-related issues in Hyderabad East.",
    associatedSchemes: ["Ayushman Bharat", "National Health Mission"],
    status: "Escalated",
    submittedAt: new Date("2026-01-03T07:00:00"),
    submittedBy: "Citizen-9012"
  },
  {
    id: "GRV-015",
    originalText: "Drain overflow causing waterlogging in residential area.",
    translatedText: "Drain overflow causing waterlogging in residential area.",
    detectedLanguage: "English",
    location: "Kolkata North",
    photoUrl: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=400",
    category: "water",
    categoryReasoning: "Identified as 'water' based on keywords: 'drain, waterlog'.",
    priority: "High",
    priorityReasoning: "Urgent issue identified: 'leak'. Requires prompt attention.",
    department: "Water Resources",
    routingReasoning: "Routed to Water Resources as the primary authority for water-related issues in Kolkata North.",
    associatedSchemes: ["Jal Jeevan Mission", "Atal Mission for Rejuvenation"],
    status: "In Progress",
    submittedAt: new Date("2026-01-03T08:30:00"),
    submittedBy: "Citizen-1234"
  },
  {
    id: "GRV-016",
    originalText: "Traffic signal not working at main junction. Very dangerous.",
    translatedText: "Traffic signal not working at main junction. Very dangerous.",
    detectedLanguage: "English",
    location: "Bangalore South",
    category: "roads",
    categoryReasoning: "Identified as 'roads' based on keywords: 'traffic, signal'.",
    priority: "High",
    priorityReasoning: "Urgent issue identified: 'danger, not working'. Requires prompt attention.",
    department: "Public Works",
    routingReasoning: "Routed to Public Works as the primary authority for roads-related issues in Bangalore South.",
    associatedSchemes: ["Pradhan Mantri Gram Sadak Yojana", "Smart Cities Mission"],
    status: "Pending",
    submittedAt: new Date("2026-01-03T09:00:00"),
    submittedBy: "Citizen-3456"
  },
  {
    id: "GRV-017",
    originalText: "Teachers not coming to government school regularly.",
    translatedText: "Teachers not coming to government school regularly.",
    detectedLanguage: "English",
    location: "Jaipur",
    category: "education",
    categoryReasoning: "Identified as 'education' based on keywords: 'teacher, school'.",
    priority: "Medium",
    priorityReasoning: "Moderate concern detected: 'problem'. Should be addressed soon.",
    department: "Education Board",
    routingReasoning: "Routed to Education Board as the primary authority for education-related issues in Jaipur.",
    associatedSchemes: ["Sarva Shiksha Abhiyan", "Mid Day Meal Scheme", "Digital India"],
    status: "Pending",
    submittedAt: new Date("2026-01-03T10:00:00"),
    submittedBy: "Citizen-7890"
  },
  {
    id: "GRV-018",
    originalText: "Man bleeding badly after accident on highway. Send ambulance!",
    translatedText: "Man bleeding badly after accident on highway. Send ambulance!",
    detectedLanguage: "English",
    location: "Delhi NCR",
    category: "healthcare",
    categoryReasoning: "Identified as 'healthcare' based on keywords: 'bleeding, ambulance, accident'.",
    priority: "Critical",
    priorityReasoning: "Emergency situation detected: 'bleeding, accident'. Immediate action required.",
    department: "Health Department",
    routingReasoning: "Routed to Health Department as the primary authority for healthcare-related issues in Delhi NCR.",
    associatedSchemes: ["Ayushman Bharat", "National Health Mission"],
    status: "Escalated",
    submittedAt: new Date("2026-01-03T10:30:00"),
    submittedBy: "Citizen-2345"
  }
];
